name: Flutter Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Создаем настройки для веб-платформы заново, чтобы гарантировать наличие всех файлов
      - name: Configure Platforms
        run: flutter create . --platforms web,android

      - name: Install dependencies
        run: flutter pub get

      # Чистая сборка Web без лишних флагов
      - name: Build Web
        run: flutter build web --release

      # Сборка Android APK
      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
