name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Init Windows support
        run: flutter create . --platforms=windows

      - name: Get dependencies
        run: flutter pub get

      - name: Build release EXE
        run: flutter build windows --release

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: matrix_app_windows
          path: build/windows/runner/Release/*.exe
